clients:
  - name: first client
    foreign_server: localhost:4000
    local_server: localhost:9200
    client_certificate: /home/ali/Desktop/reverseTunnel/client.csr
    sni: snapp.ir

servers:
  - name: first server
    listen_on: localhost:8080
    server_on: localhost:4000
    public_key_path: /home/ali/Desktop/reverseTunnel/cert.crt
    private_key_path: /home/ali/Desktop/reverseTunnel/private.key
    sni: snapp.ir
